### ISSUE TITLE
How to compile 3D models?

### ISSUE THREAD

**Issue by foxpy** [stevenalbert/3d-chess-opengl#1]
I see you store models as `.mtl` files but actual game expects `.obj` files to load and render. The question is how to compile these 3D models?
Also, code compiles in Linux flawlessly. If there is a way to compile 3D models in Linux I will happily provide simple Makefile (in pull request) for Linux folks to build this game easily.

**Comment by stevenalbert** [comment]
fixed #6

**Comment by foxpy** [comment]
Well, this issue is not resolved yet, because the actual question is how to compile these 3D models, not a request to provide precompiled ones.

**Comment by foxpy** [comment]
@stevenalbert could you reopen this issue please? I don't have access rights to do so.

**Comment by stevenalbert** [comment]
Sorry, I missed the actual question.

To compile the 3D models to `.obj` files should be done from the 3D model application.
In my case, is from SketchUp. You can `File > Export > 3D Model (and select .obj as save type)`
